export const blobArr = [
    { id: 1, title: 'Title 1', username: 'user1', submittedTime: '2025-03-01 10:00', description: 'Text Paragraph 1, Text Paragraph Text Paragraph Text Paragraph Text Paragraph' },
    { id: 2, title: 'Title 2', username: 'a', submittedTime: '2025-03-01 08:00', description: 'Text Paragraph 2, Text Paragraph Text Paragraph Text Paragraph Text Paragraph' },
    { id: 3, title: 'Title 3', username: 'user2', submittedTime: '2025-03-01 08:50', description: 'Text Paragraph 3, Text Paragraph Text Paragraph Text Paragraph Text Paragraph' },
    { id: 5, title: 'Title 4', username: 'user3', submittedTime: '2025-03-01 07:00', description: 'Text Paragraph 4, Text Paragraph Text Paragraph Text Paragraph Text Paragraph' },
    { id: 4, title: 'Title 5', username: 'a', submittedTime: '2025-03-01 07:50', description: 'Text Paragraph 5, Text Paragraph Text Paragraph Text Paragraph Text Paragraph' },
    { id: 6, title: 'Google for India 2024: Making the promise of AI real for individuals, society and the economy', username: 'a', submittedTime: '2025-03-05 21:15', description: 'Today, we hosted the tenth edition of Google for India, a milestone that invites us to reflect on the incredible transformation we have witnessed in the Indian tech landscape. Over the past decade, India has emerged as a global tech powerhouse. With the world’s lowest data prices, video became millions of Indians first handshake with the internet. UPI rewrote the boundaries of our financial networks (and digital economy) and CoWin ensured that Indians could access their health passports digitally, while the rest of the world still relied on paper. As India has embraced tech more deeply, Google’s engagement with India too has deepened over the years. From small beginnings in Bengaluru and Hyderabad in 2004, we have grown to multiple offices across 5 cities. We have seen firsthand how Indias innovative use of technology foreshadows global trends, offering a window into the future of tech. This is why were increasingly supporting global product development from India. The nations ingenuity and talent are invaluable assets in shaping the future of technology, especially in the exciting realm of AI. AI Opportunity Today, our objective is to make the promise of AI real for every Indian, illustrating the many ways it can supercharge our collective potential. AI can galvanize the ways in which every citizen can become as unlimited as their imagination, revolutionize critical areas like healthcare and agriculture, and help transform Indias demographic advantage into a true demographic dividend. AI, in essence, is a force multiplier - helping make India’s vastness manageable while also amplifying individual capabilities. To explore this further, our “AI Opportunity Agenda for India” whitepaper highlights how India can maximize AI’s potential to boost economic growth, accelerate inclusive progress and help India emerge as a global leader in public services, setting a blueprint for the world. At Google, we are committed to collaborating with the nation’s experts, innovators, and policymakers, to help India achieve her ambitious goals with AI. Were doing this by democratizing access to information, investing in infrastructure to build a thriving AI ecosystem, and equipping individuals with the skills to succeed in an AI-powered future. Naturally, the shift to AI brings to the fore, valid and urgent conversations about erecting guardrails that protect our citizens, our data and our country.. At today’s event, we also discussed the various steps we are taking to advance the cause of online safety even further.' }
];

export function addBlog(id, title, description,username,submittedTime) {
    blobArr.push({ id, title, description ,username,submittedTime});
}