export const blogCommentArr = [
    { id: 1, blogId: 1, username: 'user1', submittedTime: '2025-03-01 10:00', comment: 'This is a comment for blog 1.' },
    { id: 2, blogId: 1, username: 'user2', submittedTime: '2025-03-01 11:00', comment: 'Another comment for blog 1.' },
    { id: 3, blogId: 2, username: 'user3', submittedTime: '2025-03-02 09:00', comment: 'Comment for blog 2.' },
    { id: 4, blogId: 3, username: 'user1', submittedTime: '2025-03-03 08:00', comment: 'Comment for blog 3.' },
    { id: 5, blogId: 3, username: 'user2', submittedTime: '2025-03-03 09:30', comment: 'Another comment for blog 3.' },
    { id: 6, blogId: 3, username: 'user2', submittedTime: '2025-03-03 09:31', comment: 'comment.' },
    { id: 7, blogId: 4, username: 'a', submittedTime: '2025-03-03 09:33', comment: 'blog 3.' },
    { id: 8, blogId: 2, username: 'user3', submittedTime: '2025-03-03 09:45', comment: 'Another blog 3.' },
    { id: 9, blogId: 6, username: 'user3', submittedTime: '2025-03-05 21:17', comment: 'Breaking Down Information Barriers: With Gemini, our most powerful AI yet, were making information more accessible to people in India. Language remains core to this mission. We’re expanding Gemini Live, the Gemini apps mobile conversation experience, and AI Overviews in Google Search to more Indian languages. To help Indians seamlessly access information in ways most natural to them, we’re launching innovations across our products including a new Google Lens capability enabling you to search with video and powerful features to make your journeys more insightful, visual, and safer with Google Maps.' },
    { id: 10, blogId: 6, username: 'a', submittedTime: '2025-03-05 21:18', comment: 'Empowering businesses with AI: AI is helping businesses of all sizes stand out and thrive in the digital world. With new AI-powered tools, businesses can create captivating visuals and videos to showcase their products, update their online presence for a more immersive experience, and effectively engage customers with instant chat integrated in their Google Search listings.' },
    { id: 11, blogId: 6, username: 'user1', submittedTime: '2025-03-05 21:19', comment: 'Expanding Financial Inclusion: Google Pay is expanding access to credit in India with new offerings designed to meet the diverse needs of Indian users. This includes a new partnership with Aditya Birla Finance Limited and gold-backed loans in partnership with Muthoot Finance.' },
    { id: 12, blogId: 6, username: 'user2', submittedTime: '2025-03-05 21:20s', comment: 'Supporting digital health infrastructure: Google’s research team has been supporting the National Health Authority with thought leadership to build platforms and tools that help developers integrate apps with the digital architecture for the Ayushman Bharat Digital Mission more seamlessly. Starting next year, ABHA ID Cards will also be accessible in the Google Wallet app, in partnership with Eka Care.' }
  ];